apiVersion: v1
kind: ConfigMap
metadata:
  name: event-fusion-config
  namespace: event-fusion
  labels:
    app: event-fusion-service
data:
  # Application Configuration
  APP_NAME: "event-fusion-service"
  APP_VERSION: "1.0.0"
  ENVIRONMENT: "production"
  DEBUG: "false"
  LOG_LEVEL: "INFO"
  
  # Service Configuration
  FUSION_SERVICE_HOST: "0.0.0.0"
  FUSION_SERVICE_PORT: "8000"
  VIDEO_SERVICE_HOST: "0.0.0.0"
  VIDEO_SERVICE_PORT: "8002"
  
  # Kafka Configuration
  KAFKA_BOOTSTRAP_SERVERS: "kafka-service:9092"
  KAFKA_CONSUMER_GROUP: "event-fusion-group"
  KAFKA_AUTO_OFFSET_RESET: "latest"
  KAFKA_ENABLE_AUTO_COMMIT: "true"
  KAFKA_MAX_POLL_RECORDS: "500"
  KAFKA_SESSION_TIMEOUT_MS: "30000"
  KAFKA_HEARTBEAT_INTERVAL_MS: "10000"
  KAFKA_EVENT_TOPIC: "events"
  KAFKA_PROCESSED_TOPIC: "processed-events"
  KAFKA_VIDEO_TOPIC: "video-requests"
  
  # Redis Configuration
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  REDIS_MAX_CONNECTIONS: "100"
  REDIS_SOCKET_TIMEOUT: "5"
  REDIS_SOCKET_CONNECT_TIMEOUT: "5"
  REDIS_RETRY_ON_TIMEOUT: "true"
  REDIS_HEALTH_CHECK_INTERVAL: "30"
  
  # Elasticsearch Configuration
  ES_HOST: "elasticsearch-service"
  ES_PORT: "9200"
  ES_INDEX_PREFIX: "event-fusion"
  ES_MAX_RETRIES: "3"
  ES_RETRY_ON_TIMEOUT: "true"
  ES_TIMEOUT: "30"
  
  # Video Processing Configuration
  VIDEO_STORAGE_PATH: "/app/data/videos"
  VIDEO_TEMP_PATH: "/app/data/temp"
  VIDEO_BASE_URL: "http://video-service:8002/videos"
  VIDEO_BEFORE_SECONDS: "15"
  VIDEO_AFTER_SECONDS: "15"
  VIDEO_DEFAULT_QUALITY: "720p"
  VIDEO_DEFAULT_CODEC: "h264"
  VIDEO_RTSP_TIMEOUT: "10"
  
  # Fusion Rules Configuration
  FUSION_SILENCE_WINDOW_SECONDS: "60"
  FUSION_NEW_EVENT_THRESHOLD_SECONDS: "120"
  FUSION_EVENT_EXPIRY_SECONDS: "300"
  FUSION_ADJACENT_FUSION_DISTANCE: "1"
  FUSION_STAKES: "K0+900,K0+800,K1+000,K1+100,K1+200"
  FUSION_ADJACENT_FUSION_EVENTS: "01,04,05,06,07,08,09,15"
  
  # Performance Configuration
  PERFORMANCE_MAX_WORKERS: "4"
  PERFORMANCE_MAX_CONCURRENT_REQUESTS: "1000"
  PERFORMANCE_TASK_QUEUE_SIZE: "10000"
  PERFORMANCE_TASK_WORKER_COUNT: "10"
  PERFORMANCE_REQUEST_TIMEOUT: "30"
  PERFORMANCE_KEEP_ALIVE_TIMEOUT: "5"
  
  # Monitoring Configuration
  MONITORING_ENABLED: "true"
  MONITORING_METRICS_PORT: "9090"
  MONITORING_HEALTH_CHECK_INTERVAL: "30"
  MONITORING_LOG_REQUESTS: "true"
  MONITORING_LOG_RESPONSES: "false"
  
  # External Services Configuration
  EXTERNAL_API_TIMEOUT: "30"
  EXTERNAL_API_RETRIES: "3"
  EXTERNAL_API_BACKOFF_FACTOR: "2"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  namespace: event-fusion
  labels:
    app: kafka
data:
  server.properties: |
    broker.id=1
    listeners=PLAINTEXT://0.0.0.0:9092
    advertised.listeners=PLAINTEXT://kafka-service:9092
    num.network.threads=8
    num.io.threads=16
    socket.send.buffer.bytes=102400
    socket.receive.buffer.bytes=102400
    socket.request.max.bytes=104857600
    log.dirs=/kafka/logs
    num.partitions=3
    num.recovery.threads.per.data.dir=1
    offsets.topic.replication.factor=1
    transaction.state.log.replication.factor=1
    transaction.state.log.min.isr=1
    log.retention.hours=24
    log.retention.bytes=1073741824
    log.segment.bytes=1073741824
    log.retention.check.interval.ms=300000
    zookeeper.connect=zookeeper-service:2181
    zookeeper.connection.timeout.ms=18000
    group.initial.rebalance.delay.ms=0
    auto.create.topics.enable=true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: event-fusion
  labels:
    app: redis
data:
  redis.conf: |
    bind 0.0.0.0
    port 6379
    timeout 0
    tcp-keepalive 300
    daemonize no
    supervised no
    pidfile /var/run/redis_6379.pid
    loglevel notice
    logfile ""
    databases 16
    always-show-logo yes
    save 900 1
    save 300 10
    save 60 10000
    stop-writes-on-bgsave-error yes
    rdbcompression yes
    rdbchecksum yes
    dbfilename dump.rdb
    dir ./
    maxmemory 512mb
    maxmemory-policy allkeys-lru
    appendonly yes
    appendfilename "appendonly.aof"
    appendfsync everysec
    no-appendfsync-on-rewrite no
    auto-aof-rewrite-percentage 100
    auto-aof-rewrite-min-size 64mb
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-config
  namespace: event-fusion
  labels:
    app: elasticsearch
data:
  elasticsearch.yml: |
    cluster.name: event-fusion-cluster
    node.name: elasticsearch-node
    path.data: /usr/share/elasticsearch/data
    path.logs: /usr/share/elasticsearch/logs
    network.host: 0.0.0.0
    http.port: 9200
    discovery.type: single-node
    xpack.security.enabled: false
    xpack.monitoring.collection.enabled: true
    action.destructive_requires_name: true
  jvm.options: |
    -Xms512m
    -Xmx512m
    -XX:+UseG1GC
    -XX:G1HeapRegionSize=16m
    -XX:+UseG1GC
    -XX:+UnlockExperimentalVMOptions
    -XX:+UseCGroupMemoryLimitForHeap
    -Djava.awt.headless=true
    -Dfile.encoding=UTF-8
    -Djna.nosys=true
    -XX:-OmitStackTraceInFastThrow
    -Dio.netty.noUnsafe=true
    -Dio.netty.noKeySetOptimization=true
    -Dio.netty.recycler.maxCapacityPerThread=0
    -Dlog4j.shutdownHookEnabled=false
    -Dlog4j2.disable.jmx=true